init linux uses perl editfstab now, improved function exitonerror

diff --git a/init-linux b/init-linux
--- a/init-linux
+++ b/init-linux
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 
 # this script should be run immediately after the rpi has
 # maximised the sdcard space, or on ubuntu after install.
@@ -28,11 +28,23 @@ usage() {
 	echo "-h help"
 	exit 0
 }
-# function to log error, print error and exit
-# parameter passed: error string
+
+# function to exit with status 1
+# the debhomedev is unmounted first
+# the rc code is passed as first parameter, no exit on 0, exit on 1, 2, 3..
+# second parameter is the error string
 exitonerror() {
-	echo "$1" | tee -a ${LOGFILE}
-	exit 1;
+	# test rc code
+	if test $1 -ne 0; then
+		# display error string
+		echo "$2"
+		umount "/mnt/$DEBHOMEDEV"
+		if test $? -ne 0; then
+			echo "Could not umount $DEBHOMEDEV from /mnt/$DEBHOMEDEV"
+			exit 2;
+		fi
+		exit 1;
+	fi
 }
 
 ###############################################################
@@ -57,27 +69,14 @@ log() {
 setuplinux() {
 	# install files sudoers
 	svn export --force ${SVNURL}/root/my-linux/sudoers.d/robert /etc/sudoers.d
-	test $? -eq 0 || exitonerror "could not export sudoers.d from subversion"
+	exitonerror $? "could not export sudoers.d from subversion"
 
 	# set ownership
 	chown root:root /etc/sudoers.d/robert
 	chmod 0440 /etc/sudoers.d/robert
 
-	# setup fstab if it has not been setup already.
-	svn export --force ${SVNURL}/root/my-linux/config-files/fstab-extension /etc
-	test $? -eq 0 || exitonerror "could not export fstab-extension from subversion"
-
-	# check if fstab-extention has been added to /etc/fstab
-	grep -q "fstab-extension" /etc/fstab
-	if [ $? -ne 0 ]
-	then
-		# first backup it up
-		cp -a /etc/fstab /etc/fstab.bak
-
-		# append fstab extension to fstab
-		cat /etc/fstab-extension >> /etc/fstab
-	fi
-	# rm /etc/fstab-extension
+	# edit fstab
+	/usr/local/bin/editfstab -e
 
 	#############################################
 	# setup console boot, hostname timezone,
@@ -151,7 +150,7 @@ dtoverlay=disable-bt' /boot/config.txt
 		# note editfstab service will not exist if linux was installed
 		# from the iso image. First check if it exists
 		systemctl is-enabled editfstab > /dev/null 2>&1
-		
+
 		test $? -eq 0 && systemctl disable editfstab
 
 		# export custom.cfg from subversion
@@ -190,7 +189,7 @@ dtoverlay=disable-bt' /boot/config.txt
 setupsvn() {
 	# check new user exists
 	getent passwd $1 > /dev/null 2>&1
-	test $? -eq 0 || exitonerror "new user $1 does not exist"
+	exitonerror $? "new user $1 does not exist"
 
 	# svn is always accessed at file:///mnt/svn
 	SVNURL="file://${SVNLINK}"
@@ -206,21 +205,21 @@ setupsvn() {
 		# check if destination exists
 		if test ! -d "${SVNDESTINATION}"; then
 			mkdir -p "${SVNDESTINATION}"
-			test $? -eq 0 || exitonerror "could not make ${SVNDESTINATION}"
+			exitonerror $? "could not make ${SVNDESTINATION}"
 			chown $1:$1 "${SVNDESTINATION}"
 		fi
 		# copy files as new user
 		sudo -u $1 cp -a "/mnt/${SVNLABEL}/svn" "${SVNDESTINATION}/"
-		test $? -eq 0 || exitonerror "could not copy svn to ${SVNDESTINATION}"
+		exitonerror $? "could not copy svn to ${SVNDESTINATION}"
 
 		# setup the link, svn was moved
 		sudo -u $1 ln -s "${SVNDESTINATION}/svn" "${SVNLINK}"
-		test $? -eq 0 || exitonerror "could not make link to ${SVNDESTINATION}/svn"
+		exitonerror $? "could not make link to ${SVNDESTINATION}/svn"
 		log "made ${SVNLINK} -> ${SVNDESTINATION}/svn"
 	else
 		# svn destination not changed, set the link
 		sudo -u $1 ln -s "/mnt/${SVNLABEL}/svn" "${SVNLINK}"
-		test $? -eq 0 || exitonerror "could not make link to /mnt/${SVNLABEL}/svn"
+		exitonerror $? "could not make link to /mnt/${SVNLABEL}/svn"
 		log "made /mnt/svn -> /mnt/${SVNLABEL}/svn"
 	fi
 }
@@ -239,7 +238,7 @@ setupsvn() {
 debhome() {
 	# check new user exists
 	getent passwd $1 > /dev/null 2>&1
-	test $? -eq 0 || exitonerror "new user $1 does not exist"
+	exitonerror $? "new user $1 does not exist"
 
 	# make the link for debhome
 	# debhome is always at /mnt/debhome
@@ -258,12 +257,12 @@ debhome() {
 	test -d /etc/apt/keyrings || mkdir /etc/apt/keyrings
 	# export the public key
 	svn export --force ${SVNURL}/root/my-linux/sources/gpg/debhomepubkey.asc /etc/apt/keyrings/
-	test $? -eq 0 || exitonerror "could not export debhomepubkey.asc from subverison"
+	exitonerror $? "could not export debhomepubkey.asc from subverison"
 
 	if test "${ARCH}" = "aarch64"; then
 		# export debhome.source for arm64
 		svn export --force ${SVNURL}/root/my-linux/sources/arm64/debhome.sources /etc/apt/sources.list.d/
-		test $? -eq 0 || exitonerror "could not export debhome.sources from subversion"
+		exitonerror $? "could not export debhome.sources from subversion"
 
 		# set permissions to 0644
 		chmod 0644 /etc/apt/sources.list.d/debhome.sources
@@ -274,7 +273,7 @@ debhome() {
 	elif test "${ARCH}" = "x86_64"; then
 		# export debhome.source for amd64
 		svn export --force ${SVNURL}/root/my-linux/sources/amd64/debhome.sources /etc/apt/sources.list.d/
-		test $? -eq 0 || exitonerror "could not export debhome.sources from subversion"
+		exitonerror $? "could not export debhome.sources from subversion"
 		# set permissions to 0644
 		chmod 0644 /etc/apt/sources.list.d/debhome.sources
 
@@ -282,7 +281,7 @@ debhome() {
 		chmod 0755 /etc/apt/sources.list.d
 	else
 		# unknown architecture
-		exitonerror "unknown architecture"
+		exitonerror 1 "unknown architecture"
 	fi
 	log "setup debhome"
 }
@@ -296,20 +295,10 @@ debhome() {
 makedirs() {
 	chown $1:$1 /mnt
 
-	# make the dir list from fstab-extension
-	dirlist=`cat /etc/fstab-extension | cut -s -f1 | cut -s -d"=" -f2`
+	# make all /mnt directories
+	/usr/local/bin/editfstab -d
 
-	# dirlist="hd2 hd3 ad64 axiz axiz2 king tosh8 sah trans trans16 ver ver8 chaos ad16 xmini scd1 scd2 myp MSIRECOVERY MSISources RECOVERALL MACRIUM ele"
-	for dir in $dirlist
-	do
-		if [ ! -d /mnt/${dir} ]
-		then
-			mkdir /mnt/${dir}
-			test $? -eq 0 || exitonerror "could not make /mnt/${dir}"
-		fi
-	done
-
-	# change ownership of directories
+	# change ownership of links
 	chown --no-dereference $1:$1 /mnt/*
 	log "made directories"
 }
@@ -353,20 +342,18 @@ mountresource () {
 	# exit if label not attached
 	DEVICE=`blkid -L "$2"`
 
-	if test "$?" -ne 0; then
-		exitonerror "$2 is not attached"
-	fi
+	exitonerror $? "$2 is not attached"
 
 	# make mount directories if they do not exist
 	test -d "/mnt/$2" || mkdir "/mnt/$2"
-	test $? -eq 0 || exitonerror "could not make /mnt/$2"
+	exitonerror $? "could not make /mnt/$2"
 	chown $1:$1 "/mnt/$2"
 
 	# if not mounted mount it
 	findmnt "/mnt/$2"
 	if test $? -ne 0; then
 		mount -L "$2" "/mnt/$2"
-		test $? -eq 0 || exitonerror "could not mount $2 at /mnt/$2"
+		exitonerror $? "could not mount $2 at /mnt/$2"
 		chown $1:$1 "/mnt/$2"
 		log "mounted $2 on /mnt/$2"
 	else
@@ -378,7 +365,7 @@ mountresource () {
 	if test ! -d "/mnt/$2/$3"; then
 		# svn or archive does not exist
 		umount "/mnt/$2"
-		exitonerror "/mnt/$2/$3 not found, unmounting /mnt/$2"
+		exitonerror 1 "/mnt/$2/$3 not found, unmounting /mnt/$2"
 	else
 		log "found /mnt/$2/$3"
 	fi
@@ -444,14 +431,14 @@ accountcolours() {
 
 	# install git credentials
 	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.gitconfig /home/$1/
-	test $? -eq 0 || exitonerror "could not export .gitconfig"
+	exitonerror $? "could not export .gitconfig"
 
 	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.git-credentials /home/$1/
-	test $? -eq 0 || exitonerror "could not export .git-credentials"
+	exitonerror $? "could not export .git-credentials"
 
 	# export .bash_aliases from subversion
 	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/config-files/bash_aliases/.bash_aliases /home/$1
-	test $? -eq 0 || exitonerror "could not export .bash_aliases"
+	exitonerror $? "could not export .bash_aliases"
 
 	# edit subversion config so .git and .gitignore are ignored
 	sed -i -e 's/^# global-ignores =/global-ignores = .git .gitignore/' /etc/subversion/config
@@ -510,7 +497,7 @@ changeuser() {
 
 	# check if any process of pi is still running
 	ps -U "$1" > /dev/null 2>&1
-	test $? -eq 0 && exitonerror "a process from user $1 is still running"
+	exitonerror $? "a process from user $1 is still running"
 
 	getent passwd $2 > /dev/null 2>&1
 	if test $? -ne 0; then
@@ -601,6 +588,25 @@ if test "$0" != "/usr/local/bin/init-linux"; then
 fi
 
 ######################################
+# install git if it is not installed
+# then install editfstab
+######################################
+dpkg-query -s git > /dev/null 2>&1
+if test $? -ne 0; then
+	# install git
+	apt -y install git
+fi
+
+# use editfstab to make directories in /mnt and
+# to edit fstab so all disk drives match /mnt directories
+# get the editfstab
+test -d /tmp/editfstab && rm -rf /tmp/editfstab
+git clone -v --tags -b dev /mnt/ad64/git/initialise-linux.git /tmp/editfstab
+exitonerror $? "Could not clone editfstab"
+mv -v /tmp/editfstab /usr/local/bin/
+
+
+######################################
 # install subversion if it is not installed
 # this used to be in init-rpi
 # solves a lot of problems installing it first
@@ -608,10 +614,10 @@ fi
 dpkg-query -W subversion > /dev/null 2>&1
 if test $? -ne 0; then
 	apt update
-	test $? -eq 0 || exitonerror "error from apt update"
+	exitonerror $? "error from apt update"
 
 	apt -y install subversion
-	test $? -eq 0 || exitonerror "error installing subversion"
+	exitonerror $? "error installing subversion"
 fi
 
 #########################################
@@ -633,7 +639,7 @@ else
 		setupservice
 	else
 		# non root user is unknown
-		exitonerror "user robert or pi does not exist"
+		exitonerror 1 "user robert or pi does not exist"
 	fi
 fi
 
