inserted new setuprepository() into init_linux. setuprepository() is only invoked if debhome or svn arguments changed

diff --git a/usr/local/bin/init-linux b/usr/local/bin/init-linux
--- a/usr/local/bin/init-linux
+++ b/usr/local/bin/init-linux
@@ -224,7 +224,6 @@ setuplinux() {
 	fi
 }
 
-#########################################################
 # function to setup subversion link to the new path
 # the new user must already exist
 # the owner.group of the /mnt directory must
@@ -233,21 +232,49 @@ setuplinux() {
 # to point to it.
 # parameters: setupreppository
 # 		$1 CURUSER  (non root)
-#		$2 svnpath | debhomepath
-#		$3 link  (/mnt/svn/ | /mnt/debhome)
-#		$4 debhome | svn device which may not be necessary
+#		$2 svnpath roor dir | debhomepath root dir
+#		$3 svn | debhome , just the name to distuigish which one is being set up
 #########################################################
 setuprepository() {
+	# the links /mnt/svn and /mnt/debhome never change.
+	# set them so they do not have to be passed as arguments
+	# to this function
+	
 	# check new user exists
-	getent passwd $1 > /dev/null 2>&1
+	/usr/bin/getent passwd "$1" > /dev/null 2>&1 
 	exitonerror $? "new user $1 does not exist"
+
+	# the argument $2 is the debhome root directory.
+	# default is /mnt/ad64/debhome with link /mnt/debhome.
+	# to check the existence of the debhome repository
+	# use /debian_root_directory/dists/home.
+	# only do this for debhome, not svn
+	if test "$3" = "debhome"; then
+		# set the full path of debhome for a better check
+		REPOSITORY_PATH="$2/dists/home"
+		# set the link
+		REPOSITORY_LINK="${DEBHOME_LINK}"
+
+	elif test "$3" = "svn"; then
+		# set the path for svn check
+		REPOSITORY_PATH="$2/db"
+		# set the link
+		REPOSITORY_LINK="${SVN_LINK}"
+	else
+		# $3 should be svn or debhome
+		# but it is something else.
+		# print and error message and exit
+		exitonerror 1 "\$3 = $3, should be svn or debhome"
+	fi
+	echo "respository path = ${REPOSITORY_PATH}"
+	echo "repository link = ${REPOSITORY_LINK}"
 
 	# makelive now makes directories /mnt/debhome
 	# and /mnt/svn to access svn and debhome.
 	# makelive delets these directories
 
 	# set ownership of /mnt to robert:robert
-	chown $1:$1 /mnt
+	/usr/bin/chown $1:$1 /mnt
 
 	# check that there is not a directory with the name of the link.
 	# remove it or fail
@@ -255,90 +282,127 @@ setuprepository() {
 	# so a link can be made.
 	# test -d link gives true if link points to a directory.
 	# hence test for directory must be
-	# if file exists and is not a link and is a directory
-	if test -e "${3}" && test ! -L "${3}" && test -d "${3}"; then
-		echo "${3} is a directory, removing .."
-		rmdir -v "${3}"
-		exitonerror $? "Could not remove directory ${3}"
+	# if file or directory exists with the name of the link , /mnt/svn or /mnt/debhome, remove it
+	if test -e "${REPOSITORY_LINK}" && test ! -L "${REPOSITORY_LINK}" && test -d "${REPOSITORY_LINK}"; then
+		echo "${REPOSITORY_LINK} is a directory, removing .."
+		rmdir -v "${REPOSITORY_LINK}"
+		exitonerror $? "Could not remove directory ${REPOSITORY_LINK}"
 	fi
 
 	# check that repository can be found
-	# at the path
-	if test -d "$2"; then
+	# by using the full path to the repository
+	# for debhome /debhome_root_directory/dists/home
+	# for svn /svn_root_directory
+	# REPOSITORY_PATH is set for each repository
+	if test -d "${REPOSITORY_PATH}"; then
 		# path exists now check the link
-		if test -L "$3"; then
+		if test -L "${REPOSITORY_LINK}"; then
 			# the link exists
 			# check where it points to
-			LINKPATH=`ls -l $3 | cut -d " " -f11`
+			LINKPATH=`ls -l ${REPOSITORY_LINK} | cut -d " " -f11`
 
-			# now check if link points to svn | debhome path
+			# now check if link points to svn | debhome root directory
 			if test "${LINKPATH}" != "$2"; then
 				# link must be changed
-				rm -vf "$3"
-				exitonerror $? "could not remove link $3"
+				rm -vf "${REPOSITORY_LINK}"
+				exitonerror $? "could not remove link ${REPOSITORY_LINK}"
 				# make the new link
-				sudo -u $1 ln -s "$2" "$3"
-				exitonerror $? "could not make the link $3"
+				sudo -u $1 ln -s "$2" "${REPOSITORY_LINK}"
+				exitonerror $? "could not make the link ${REPOSITORY_LINK}"
 			fi
 
 		else
 			# there is no link
 			# make the link
-			sudo -u $1 ln -s "$2" "$3"
-			exitonerror $? "could not make the link $3"
+			sudo -u $1 ln -s "$2" "${RESPOSITORY_LINK}"
+			exitonerror $? "could not make the link ${RESPOSITORY_LINK}"
 		fi
 		# subversion | debhome exists and link is correct
-		echo "old link -> ${LINKPATH} new link -> $2"
-		log "repository exists $3 -> $2"
+		echo "repository exists at ${REPOSITORY_LINK} -> $2"
 
 	else
-		# full path does not exist to repository
+		# repository path is not valid
+		# it may reside on a device that is attached
+		# and needs to be mounted
 		# try and mount debhome | svn device
-		test -d "/mnt/$4" || sudo -u $1 mkdir "/mnt/$4"
-		exitonerror $? "could not make directory /mnt/$4"
+		echo "repository does not exist at $2"
 
-		# mount the device if not mounted
-		# check where it is mounted
-		# should be on /mnt/$4
-		findmnt --source LABEL="$4"
-		if test $? -eq 0; then
-			# device is mounted
-			# get mountpoint
-			MNTPT=`findmnt --source LABEL="$4" -o TARGET | sed -n -e '2p'`
-			echo "$4 is mounted at ${MNTPT}"
+		# the repository root directories could be
+		# /mnt/device/debhome | svn
+		# /opt/debhome | svn etc
+		# determine if an attached device is in the root directory
+		# get the device part from /mnt/device/debhome | svn
+		DEVICE=`echo "$2" | cut -d "/" -f3`
+		
+		# check if device is attached
+		lsblk -o LABEL | grep -w "${DEVICE}"
+		if test $? -eq 0; then 
+			# this is a valid device
+			# and it is attached.
+			echo "${DEVICE} is a valid attached device -- attempting to mount ${DEVICE}"
 
-			# if mount point is not /mnt/$4
-			# then umount and mount again
-			if test "${MNTPT}" != "/mnt/$4"; then
-				# mounted but not at /mnt/$4
-				umount "${MNTPT}"
-				exitonerror $? "could not umount ${MNTPT}"
-				# mount it correctly
-				mount -v -L "$4" "/mnt/$4"
-				exitonerror $? "could not mount $4 at /mnt/$4"
+			test -d "/mnt/${DEVICE}" || sudo -u $1 mkdir "/mnt/${DEVICE}"
+			exitonerror $? "could not make directory /mnt/${DEVICE}"
+
+			# the repository root directory $2 is of
+			# the form /directory/debhome OR /mnt/device_label/debhome
+			# determine if the string contains a valid device label
+			# mount the device if not mounted
+			# check where it is mounted
+			# should be on /mnt/$DEVICE
+			findmnt --source LABEL="${DEVICE}"
+			if test $? -eq 0; then
+				# device is mounted
+				# get mountpoint
+				MNTPT=`findmnt --source LABEL="${DEVICE}" -o TARGET | sed -n -e '2p'`
+				echo "${DEVICE} is mounted at ${MNTPT}"
+
+				# if mount point is not /mnt/DEVICE
+				# then umount and mount again
+				if test "${MNTPT}" != "/mnt/${DEVICE}"; then
+					# mounted but not at /mnt/$DEVICE
+					umount "${MNTPT}"
+					exitonerror $? "could not umount ${MNTPT}"
+					# mount it correctly
+					mount -v -L "${DEVICE}" "/mnt/${DEVICE}"
+					exitonerror $? "could not mount ${DEVICE} at /mnt/${DEVICE}"
+				fi
+			else
+				# DEVICE is not mounted
+				mount -v -L "${DEVICE}" "/mnt/${DEVICE}"
+				exitonerror $? "could not mount ${DEVICE} at /mnt/${DEVICE}"
 			fi
-		else
-			# $4 is not mounted
-			mount -v -L "$4" "/mnt/$4"
-			exitonerror $? "could not mount $4 at /mnt/$4"
 		fi
 
 		# remove and make the link for subversion | debhome
-		rm -vf "$3"
-		sudo -u $1 ln -v -s "$2" "$3"
-		exitonerror $? "could not make the link $3"
+		rm -vf "${REPOSITORY_LINK}"
+		sudo -u $1 ln -s "$2" "${REPOSITORY_LINK}"
+		exitonerror $? "could not make the link ${REPOSITORY_LINK}"
 
 		# check that the repository exists from the link
-		test -d "$3" || exitonerror 1 "repository not found at $2"
+		if test -d "${REPOSITORY_PATH}"; then
+			# repository exists
+			echo "repository exists at ${REPOSITORY_LINK} -> $2"
+		else
+			# repository not found
+			# enter the root directory to the repository and try again
+			until test -d "${REPOSITORY_PATH}"; do
+				# prompt for a new path to 
+				echo "The link ${REPOSITORY_LINK} -> $2 which is invalid"
+				echo "Enter the root directory that ${REPOSITORY_LINK} points to"
+				read REPOSITORY_ROOT_DIR
+				# try again
+				setuprepository "robert" "${REPOSITORY_ROOT_DIR}" "${3}"
+			done
 
 		# subversion | debhome exists and link is correct
-		log "repository exists $3 -> $2"
+		fi
 
 	fi
 	# repository exists
-
-
 }
+
+
 
 ###########################################
 # make all the mount directories
@@ -483,9 +547,9 @@ installprerequisites() {
 usage() {
 	echo "-g set target to graphical target               default: ${TARGET}";
 	echo "-n set target to multi-user.target	        default: ${TARGET}";
-	echo "-d full path to debhome				default: ${DEBHOMEPATH}";
+	echo "-d full path to debhome root			default: ${DEBHOMEPATH}";
 	echo "-D debhome default device			default: ${DEBHOMEDEVICE}";
-	echo "-s full path to svn      			default: ${SVNPATH}";
+	echo "-s full path to svn root      			default: ${SVNPATH}";
 	echo "-S svn device					default: ${SVNDEVICE}";
    	echo "-V version and exit";
    	echo "-L run in chrootenvironment";
@@ -506,6 +570,8 @@ DEBHOMEDEVICE="ad64"
 DEBHOMEPATH="/mnt/${DEBHOMEDEVICE}/debhome"
 SVNDEVICE="ad64"
 SVNPATH="/mnt/${SVNDEVICE}/svn"
+SVN_LINK="/mnt/svn"
+DEBHOME_LINK="/mnt/debhome"
 LOGFILE="/tmp/init-linux.log"
 # the current non root user, either robert or pi
 CURUSER="robert"
@@ -519,16 +585,15 @@ ARCH=`arch`
 LIVEINSTALL="false"
 
 ################################
-# constants which never change
-################################
-DEBHOMELINK="/mnt/debhome"
-SVNLINK="/mnt/svn"
-SVNURL="file:///${SVNLINK}"
-
-################################
 # main entry
 ################################
 
+# flags to indicate if setuprepository() must be invoked
+# if the path or device for the repository changes
+# setuprepository() must be invoked
+# this applies to svn and debhome
+DEBHOME_FLAG="false"
+SVN_FLAG="false"
 
 # init-linux must not be run on a live system
 if test `hostname` = "live"; then
@@ -542,12 +607,12 @@ fi
 while getopts gnd:D:s:S:VhL opt
 do
 	case ${opt} in
-		d) DEBHOMEPATH="${OPTARG}";;
+		d) DEBHOMEPATH="${OPTARG}"; DEBHOME_FLAG="true";;
 		g) TARGET="graphical.target";;
 		n) TARGET="multi-user.target";;
-		D) DEBHOMEDEVICE="${OPTARG}";;
-		s) SVNPATH="${OPTARG}";;
-		S) SVNDEVICE="${OPTARG}";;
+		D) DEBHOMEDEVICE="${OPTARG}"; DEBHOME_FLAG="true";;
+		s) SVNPATH="${OPTARG}"; SVN_FLAG="true";;
+		S) SVNDEVICE="${OPTARG}" SVN_FLAG="true";;
 		L) LIVEINSTALL="true";;
 		V) dpkg-query -W "initialise-linux"; exit 0;;
 		h) usage;;
@@ -603,8 +668,10 @@ fi
 if test "${LIVEINSTALL}" = "false"; then
 	# debhome must be done before svn since the link is required
 	# to copy debhomepubkey.asc and debhome.sources from /mnt/debhome
-	setuprepository "${CURUSER}" "${DEBHOMEPATH}" "${DEBHOMELINK}" "${DEBHOMEDEVICE}"
-	setuprepository "${CURUSER}" "${SVNPATH}" "${SVNLINK}" "${SVNDEVICE}"
+	# setuprepository is only invoked if DEBHOME_FLAG is true.
+	# same for svn.
+	test "${DEBHOME_FLAG}" = "true" && setuprepository "${CURUSER}" "${DEBHOMEPATH}" "debhome"
+	test "${SVN_FLAG}" = "true" && setuprepository "${CURUSER}" "${SVNPATH}" "svn"
 
 	# for rpi copy debhome-rpi.sources
 	if test "${ARCH}" = "aarch64"; then
