svn now exports even if the file exists. They are overwritten

diff --git a/usr/local/bin/init-linux b/usr/local/bin/init-linux
--- a/usr/local/bin/init-linux
+++ b/usr/local/bin/init-linux
@@ -78,10 +78,8 @@ log() {
 ###################################
 setuplinux() {
 	# install files sudoers
-	if test ! -f "/etc/sudoers.d/robert"; then
-		svn export --force ${SVNURL}/root/my-linux/sudoers.d/robert /etc/sudoers.d
-		exitonerror $? "could not export sudoers.d from subversion"
-	fi
+	svn export --force ${SVNURL}/root/my-linux/sudoers.d/robert /etc/sudoers.d
+	exitonerror $? "could not export sudoers.d from subversion"
 
 	# set ownership
 	chown root:root /etc/sudoers.d/robert
@@ -313,12 +311,11 @@ setuprepository() {
 	if test "$3" = "${DEBHOMELINK}"; then
 		# debhome is being set up
 		# get the public key
-		if test ! -f "/etc/apt/keyrings/debhomepubkey.asc"; then
-			# mkdir /etc/apt/keyrings if it does not exist
-			test -d /etc/apt/keyrings || mkdir /etc/apt/keyrings
-			svn export --force ${SVNURL}/root/my-linux/sources/gpg/debhomepubkey.asc /etc/apt/keyrings/
-			exitonerror $? "could not export debhomepubkey.asc from subverison"
-		fi
+		# mkdir /etc/apt/keyrings if it does not exist
+		test -d /etc/apt/keyrings || mkdir /etc/apt/keyrings
+		svn export --force ${SVNURL}/root/my-linux/sources/gpg/debhomepubkey.asc /etc/apt/keyrings/
+		exitonerror $? "could not export debhomepubkey.asc from subverison"
+
 		# get debhome.sources for amd64 or rpi
 		if test "${ARCH}" = "aarch64"; then
 			if test ! -f "/etc/apt/sources.list.d/debhome.sources"; then
@@ -334,17 +331,15 @@ setuprepository() {
 			fi
 
 		elif test "${ARCH}" = "x86_64"; then
-			if test ! -f "/etc/apt/sources.list.d/debhome.sources"; then
-				# export debhome.source for amd64
-				svn export --force ${SVNURL}/root/my-linux/sources/amd64/debhome.sources /etc/apt/sources.list.d/
-				exitonerror $? "could not export debhome.sources from subversion"
+			# export debhome.source for amd64
+			svn export --force ${SVNURL}/root/my-linux/sources/amd64/debhome.sources /etc/apt/sources.list.d/
+			exitonerror $? "could not export debhome.sources from subversion"
 
-				# set permissions to 0644
-				chmod 0644 /etc/apt/sources.list.d/debhome.sources
+			# set permissions to 0644
+			chmod 0644 /etc/apt/sources.list.d/debhome.sources
 
-				# set permisions of directory
-				chmod 0755 /etc/apt/sources.list.d
-			fi
+			# set permisions of directory
+			chmod 0755 /etc/apt/sources.list.d
 		else
 			# unknown architecture
 			exitonerror 1 "unknown architecture ${ARCH}"
@@ -458,42 +453,34 @@ accountcolours() {
 	sudo -u $1 sed -i -e 's/\[\\033\[01;34m\\\]/\[\\033\[01;36m\\\]/' /home/$1/.bashrc
 
 	# install git config
-	if test ! -f "/home/$1/.gitconfig"; then
-		sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.gitconfig /home/$1/
-		exitonerror $? "could not export .gitconfig"
-	fi
+	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.gitconfig /home/$1/
+	exitonerror $? "could not export .gitconfig"
 
 	# install config for gh
 	# the file is gh.tgz so that the git password can be uploaded to github
 	# it must be unarchived
-	if test ! -f "/home/$1/.config/gh/config.yml"; then
-		sudo -u $1 svn export --force ${SVNURL}/root/my-linux/gh/gh.tgz /home/$1/.config
-		exitonerror $? "could not export gh.tgz"
-		#unarchive gh.tgz
-		cd /home/$1/.config
-		tar -xvzf gh.tgz
-		rm -vf gh.tgz
-	fi
+	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/gh/gh.tgz /home/$1/.config
+	exitonerror $? "could not export gh.tgz"
+	#unarchive gh.tgz
+	cd /home/$1/.config
+	tar -xvzf gh.tgz
+	rm -vf gh.tgz
 
 	# install git credentials
-	if test ! -f "/home/$1/.git-credentials"; then
-		sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.git-credentials /home/$1/
-		exitonerror $? "could not export .git-credentials"
-		# git-credentials contains special characters in the pat so that github
-		# could not detect the pat. If the pat is detected it is revoked.
-		# the special characters must be removed.
-		# special character is ;
-		# perl code below is for a ONE LINE git-credentials ONLY
-		perl -W -e 'open(GC, "<", "/home/robert/.git-credentials") or die "could not open git-credentials: $!\n"; my $line = <GC>; close GC; chomp($line); $line =~ s/;//g; open(GC, ">", "/home/robert/.git-credentials") or die "Could not open git-credentials for writing:$!\n"; print GC "$line\n"; close GC;';
+	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/git/.git-credentials /home/$1/
+	exitonerror $? "could not export .git-credentials"
+	# git-credentials contains special characters in the pat so that github
+	# could not detect the pat. If the pat is detected it is revoked.
+	# the special characters must be removed.
+	# special character is ;
+	# perl code below is for a ONE LINE git-credentials ONLY
+	perl -W -e 'open(GC, "<", "/home/robert/.git-credentials") or die "could not open git-credentials: $!\n"; my $line = <GC>; close GC; chomp($line); $line =~ s/;//g; open(GC, ">", "/home/robert/.git-credentials") or die "Could not open git-credentials for writing:$!\n"; print GC "$line\n"; close GC;';
 
-	fi
 
 	# install rclone.conf
-	if test ! -f "/home/$1/.config/rclone/rclone.conf"; then
-		test -d /home/$1/.config || mkdir /home/$1/.config
-		sudo -u $1 svn export --force ${SVNURL}/root/my-linux/rclone /home/$1/.config/rclone
-		exitonerror $? "could not export rclone  config"
-	fi
+	test -d /home/$1/.config/rclone || mkdir -p /home/$1/.config/rclone
+	sudo -u $1 svn export --force ${SVNURL}/root/my-linux/rclone /home/$1/.config/rclone
+	exitonerror $? "could not export rclone  config"
 
 	# export .bash_aliases from subversion
 	# it must be overwritten as it exists
