postinst, prerm only delete keys if they exist in keyring. new keys for testing

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -72,8 +72,15 @@ if test -f "/tmp/initialise-linux-status"; then
 				if test ${RC} -ne 0; then
 					# new key does not exist in the current list
 					# delete the public key and the secret key from /mnt/debhome/currentkeyid
-					gpg --batch --yes --pinentry-mode loopback --delete-secret-key "${CURRENTKEYID}"
-					gpg --batch --yes --delete-key "${CURRENTKEYID}"
+					# only if the key is in the keyring
+					gpg --list-secret-keys "${CURRENTKEYID}"
+					if test $? -eq 0; then
+						gpg --batch --yes --pinentry-mode loopback --delete-secret-key "${CURRENTKEYID}"
+						gpg --batch --yes --delete-key "${CURRENTKEYID}"
+					else
+						# key not found in keyring
+						echo "initialise-linux:posinst:upgrade: {CURRENTKEYID} not found in keyring: cannot delete"
+					fi
 					
 					# import the new secret key
 					# not necessary to import the public key
@@ -100,7 +107,7 @@ if test -f "/tmp/initialise-linux-status"; then
 				# cannot determine the key id
 				echo " "
 				echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-				echo "postinst: Cannot determine the new key id as /etc/apt/keyrings/debhomepubkey.gpg not found"
+				echo "initialise-linux:postinst:upgrade: Cannot determine the new key id as /etc/apt/keyrings/debhomepubkey.gpg not found"
 				echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 				
 				# wait for a prompt or time out of 5 seconds
@@ -218,7 +225,7 @@ if test -f "/tmp/initialise-linux-status"; then
 else
 	# there is no file /tmp/initialise-linux-status
 	echo "+++++++++++++++++++++++++++++++++++++++++++++"
-	echo "There is no file /tmp/initialise-linux-status"
+	echo "initialise-linux:postinst: There is no file /tmp/initialise-linux-status"
 	echo "cannot import or delete gpg keys"
 	echo "+++++++++++++++++++++++++++++++++++++++++++++"
 	read -t 5 value
diff --git a/DEBIAN/prerm b/DEBIAN/prerm
--- a/DEBIAN/prerm
+++ b/DEBIAN/prerm
@@ -31,21 +31,28 @@ if test "$1" = "remove"; then
 		# get the key without leading spaces
 		CURRENTKEYID=`cat /tmp/currentkeyid.txt`
 
-		# delete the keys from the keyring
-		echo "initialise-linux:prerm: deleting secret and public keys [${CURRENTKEYID}]"
+		# delete the current key only if it is in the keyring
+		gpg --list-secret-keys "${CURRENTKEYID}"
+		if test $? -eq 0; then
+			# delete the keys from the keyring
+			echo "initialise-linux:prerm:remove: deleting secret and public keys [${CURRENTKEYID}]"
 		
-		gpg --batch --yes --pinentry-mode loopback --delete-secret-keys "${CURRENTKEYID}"
+			gpg --batch --yes --pinentry-mode loopback --delete-secret-keys "${CURRENTKEYID}"
 
-		# delete the public key only if the secret key has been deleted
-		gpg --batch --yes --delete-keys "${CURRENTKEYID}"
+			# delete the public key only if the secret key has been deleted
+			gpg --batch --yes --delete-keys "${CURRENTKEYID}"
+		else
+			# key not found
+			echo "initialise-linux:prerm:remove: ${CURRENTKEYID} not found in keyring"
+		fi
 		
 		# the file debhomepubkey.gpg will be automatically removed when the 
 		# package is removed.
 	else
 		# the file /etc/apt/keyrings/debhomepubkey.gpg does not exist
 		# print and error message and continue
-		echo "initialise-linux:prerm: The file /etc/apt/keyrings/debhomepubkey.gpg was not found"
-		echo "initialise-linux:prerm: The secret and public key could not be deleted"
+		echo "initialise-linux:prerm:remove: The file /etc/apt/keyrings/debhomepubkey.gpg was not found"
+		echo "initialise-linux:prerm:remove: The secret and public key could not be deleted"
 		read -t 5 value
 	fi
 
